// Auto-generated by GitHub Action. Unit: RM/gram
// Structure: { "TYPE": { history: [{date: "YYYY-MM-DD", value: INT}] } }
window.goldPrices = {
  "835": {
    "history": [
      {
        "date": "2025-08-04",
        "value": 346
      },
      {
        "date": "2025-08-05",
        "value": 347
      },
      {
        "date": "2025-08-08",
        "value": 347
      },
      {
        "date": "2025-08-24",
        "value": 345
      },
      {
        "date": "2025-08-25",
        "value": 341
      },
      {
        "date": "2025-08-26",
        "value": 382
      }
    ]
  },
  "916": {
    "history": [
      {
        "date": "2025-08-04",
        "value": 405
      },
      {
        "date": "2025-08-05",
        "value": 407
      },
      {
        "date": "2025-08-08",
        "value": 407
      },
      {
        "date": "2025-08-24",
        "value": 404
      },
      {
        "date": "2025-08-25",
        "value": 399
      },
      {
        "date": "2025-08-26",
        "value": 419
      }
    ]
  },
  "999": {
    "history": [
      {
        "date": "2025-08-04",
        "value": 446
      },
      {
        "date": "2025-08-05",
        "value": 449
      },
      {
        "date": "2025-08-08",
        "value": 442
      },
      {
        "date": "2025-08-24",
        "value": 439
      },
      {
        "date": "2025-08-25",
        "value": 434
      },
      {
        "date": "2025-08-26",
        "value": 457
      }
    ]
  },
  "999.9P": {
    "history": [
      {
        "date": "2025-08-04",
        "value": 454
      },
      {
        "date": "2025-08-05",
        "value": 455
      },
      {
        "date": "2025-08-08",
        "value": 452
      },
      {
        "date": "2025-08-24",
        "value": 449
      },
      {
        "date": "2025-08-25",
        "value": 444
      },
      {
        "date": "2025-08-26",
        "value": 458
      }
    ]
  },
  "999.9": {
    "history": [
      {
        "date": "2025-08-04",
        "value": 450
      },
      {
        "date": "2025-08-05",
        "value": 451
      },
      {
        "date": "2025-08-08",
        "value": 446
      },
      {
        "date": "2025-08-24",
        "value": 443
      },
      {
        "date": "2025-08-25",
        "value": 438
      },
      {
        "date": "2025-08-26",
        "value": 458
      }
    ]
  }
};
