// Auto-generated by GitHub Action. Unit: RM/gram
// window.goldPrices: 市场价历史；window.storePrices: 门店卖价（按 999×系数）；window.storeDiffs: 卖价涨跌
window.goldPrices = {
  "835": {
    "history": [
      {
        "date": "2025-08-04",
        "value": 346
      },
      {
        "date": "2025-08-05",
        "value": 347
      },
      {
        "date": "2025-08-08",
        "value": 347
      },
      {
        "date": "2025-08-24",
        "value": 345
      },
      {
        "date": "2025-08-25",
        "value": 341
      },
      {
        "date": "2025-08-26",
        "value": 384
      },
      {
        "date": "2025-08-27",
        "value": 383
      }
    ]
  },
  "916": {
    "history": [
      {
        "date": "2025-08-04",
        "value": 405
      },
      {
        "date": "2025-08-05",
        "value": 407
      },
      {
        "date": "2025-08-08",
        "value": 407
      },
      {
        "date": "2025-08-24",
        "value": 404
      },
      {
        "date": "2025-08-25",
        "value": 399
      },
      {
        "date": "2025-08-26",
        "value": 421
      },
      {
        "date": "2025-08-27",
        "value": 420
      }
    ]
  },
  "999": {
    "history": [
      {
        "date": "2025-08-04",
        "value": 446
      },
      {
        "date": "2025-08-05",
        "value": 449
      },
      {
        "date": "2025-08-08",
        "value": 442
      },
      {
        "date": "2025-08-24",
        "value": 439
      },
      {
        "date": "2025-08-25",
        "value": 434
      },
      {
        "date": "2025-08-26",
        "value": 459
      },
      {
        "date": "2025-08-27",
        "value": 458
      }
    ]
  },
  "999.9P": {
    "history": [
      {
        "date": "2025-08-04",
        "value": 454
      },
      {
        "date": "2025-08-05",
        "value": 455
      },
      {
        "date": "2025-08-08",
        "value": 452
      },
      {
        "date": "2025-08-24",
        "value": 449
      },
      {
        "date": "2025-08-25",
        "value": 444
      },
      {
        "date": "2025-08-26",
        "value": 460
      },
      {
        "date": "2025-08-27",
        "value": 459
      }
    ]
  },
  "999.9": {
    "history": [
      {
        "date": "2025-08-04",
        "value": 450
      },
      {
        "date": "2025-08-05",
        "value": 451
      },
      {
        "date": "2025-08-08",
        "value": 446
      },
      {
        "date": "2025-08-24",
        "value": 443
      },
      {
        "date": "2025-08-25",
        "value": 438
      },
      {
        "date": "2025-08-26",
        "value": 460
      },
      {
        "date": "2025-08-27",
        "value": 459
      }
    ]
  }
};
window.storePrices = {
  "999.9 BAR(P)": 447,
  "999.9 BAR": 441,
  "999 GOLD": 437,
  "916 GOLD": 402,
  "835 GOLD": 343
};
window.storeDiffs = {
  "999.9 BAR(P)": -1,
  "999.9 BAR": -1,
  "999 GOLD": -1,
  "916 GOLD": -1,
  "835 GOLD": -1
};
